[local]
localhost

[mongodb]
localhost

[catalogue]
catalogue-dev.daws88ss.online

[redis]
localhost

[user]
user-dev.daws88ss.online

[cart]
cart-dev.daws88ss.online

[mysql]
mysql-dev.daws88ss.online

[shipping]
shipping-dev.daws88ss.online

[rabbitmq]
rabbitmq-dev.daws88ss.online

[payment]
payment-dev.daws88ss.online

[frontend]
frontend-dev.daws88ss.online